# master
- project:
    name: ceph-ansible-prs-master-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - dev
    distribution:
      - centos
      - ubuntu
    deployment:
      - container
      - non_container
    scenario:
      - all_daemons
      - cluster
      - collocation
      - update
      - lvm_osds
      - shrink_mon
      - shrink_osd
      - lvm_batch
      - add_osds
      - add_mons
      - add_mdss
      - rgw_multisite
      - purge
      - lvm_auto_discovery
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-master-non_container-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - dev
    distribution:
      - centos
      - ubuntu
    deployment:
      - non_container
    scenario:
      - switch_to_containers
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-master-ooo-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - dev
    distribution:
      - centos
    deployment:
      - container
    scenario:
      - ooo_collocation
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-master-podman-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - dev
    distribution:
      - rhel
    deployment:
      - container
    scenario:
      - podman
    jobs:
        - 'ceph-ansible-prs-pipeline'

# nautilus
- project:
    name: ceph-ansible-prs-nautilus-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - nautilus
    distribution:
      - centos
      - ubuntu
    deployment:
      - container
      - non_container
    scenario:
      - all_daemons
      - cluster
      - collocation
      - update
      - lvm_osds
      - shrink_mon
      - shrink_osd
      - lvm_batch
      - add_osds
      - add_mons
      - add_mdss
      - rgw_multisite
      - purge
      - lvm_auto_discovery
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-nautilus-non_container-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - nautilus
    distribution:
      - centos
      - ubuntu
    deployment:
      - non_container
    scenario:
      - switch_to_containers
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-nautilus-ooo-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - nautilus
    distribution:
      - centos
    deployment:
      - container
    scenario:
      - ooo_collocation
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-nautilus-podman-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - nautilus
    distribution:
      - rhel
    deployment:
      - container
    scenario:
      - podman
    jobs:
        - 'ceph-ansible-prs-pipeline'

# luminous, stable-3.2, stable 3.1
- project:
    name: ceph-ansible-prs-luminous-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - luminous
    distribution:
      - centos
      - ubuntu
    deployment:
      - container
      - non_container
    scenario:
# stable-3.2 / stable-3.1
      - all_daemons
      - collocation
      - update
      - lvm_osds
      - shrink_mon
      - shrink_osd
      - lvm_batch
      - add_osds
      - rgw_multisite
      - purge
# stable-3.1
      - filestore_osds
      - purge_filestore
      - bluestore_osds
      - purge_bluestore
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-stable-ooo-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - luminous
    distribution:
      - centos
    deployment:
      - container
    scenario:
      - ooo_collocation
    jobs:
        - 'ceph-ansible-prs-pipeline'

- project:
    name: ceph-ansible-prs-stable-non_container-pipeline
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - luminous
    distribution:
      - centos
      - ubuntu
    deployment:
      - non_container
    scenario:
      - switch_to_containers
    jobs:
        - 'ceph-ansible-prs-pipeline'

- job-template:
    name: 'ceph-ansible-prs-{release}-{distribution}-{deployment}-{scenario}'
    id: 'ceph-ansible-prs-pipeline'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release}-{distribution}-{deployment}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*|.*\[skip ci\].*'
          trigger-phrase: '^jenkins test {release}-{distribution}-{deployment}-{scenario}|jenkins test all.*'
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release}-{distribution}-{deployment}-{scenario}"
          started-status: "Running: {release}-{distribution}-{deployment}-{scenario}"
          success-status: "OK - {release}-{distribution}-{deployment}-{scenario}"
          failure-status: "FAIL - {release}-{distribution}-{deployment}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            DEPLOYMENT={deployment}
            DISTRIBUTION={distribution}
            RELEASE={release}
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            # Returns 1 if only .rst and README files were modified
            echo "Checking if only rst and READMEs were modified"
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep -v '\.rst\|README'
            if [ $? -eq 1 ]; then
              echo "Only docs were modified.  Skipping the rest of the job."
              exit 1
            fi
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw-escape:
                  - ../../../scripts/build_utils.sh
                  - ../../build/build

    publishers:
      - naginator:
          max-failed-builds: 3
          regular-expression: "Failure talking to yum|Call to virDomainLookupByUUID failed"

      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false


# tests that will not auto start when a PR is created, but
# they can be requested with a trigger phrase. Run on smithi.
- project:
    name: ceph-ansible-prs-oldstable
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - luminous
    scenario:
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_non_container
      - purge_filestore_osds_container
      - update_cluster
      - update_docker_cluster
      - switch_to_containers
      - bluestore_osds_non_container
      - filestore_osds_non_container
      - filestore_osds_container
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - lvm_osds
      - lvm_batch
      - purge_lvm_osds
      - lvm_osds_container
      - lvm_batch_container
      - add_osds
      - add_osds_container
      - rgw_multisite
      - rgw_multisite_container
      - lvm_auto_discovery
      - lvm_auto_discovery_container
    jobs:
        - 'ceph-ansible-prs-oldstable'

- job-template:
    name: 'ceph-ansible-prs-{release}-{scenario}'
    id: 'ceph-ansible-prs-oldstable'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*|.*\[skip ci\].*'
          trigger-phrase: '^jenkins test {release}-{scenario}|jenkins test all.*'
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release}-{scenario}"
          started-status: "Running: {release}-{scenario}"
          success-status: "OK - {release}-{scenario}"
          failure-status: "FAIL - {release}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false
